### ISSUE TITLE
There is issue with filereplace module as this doesn't replace the pattern on last line.

### ISSUE THREAD

**Issue by okmahendra** [MisterL2/python-util#2]
from pyutil import filereplace
[somefile.txt](https://github.com/MisterL2/python-util/files/4809283/somefile.txt)

filereplace("somefile.txt","abcd","ram")

**Comment by MisterL2** [comment]
Sorry, did not see this issue for a long time 😅 
Issue has been fixed and new version is now pushed to the repository. Will be updated on pip today/tomorrow.
Thanks for contributing!
Let me know if you have any feature suggestions etc :)
