### ISSUE TITLE
error with filereplace()

### ISSUE THREAD

**Issue by Leytoncito** [MisterL2/python-util#3]
when i try:

for seq, gen in zip(sequence, gene):
    filereplace(gml_in,seq,gen)

I previously extracted these arrays from a csv using pandas and numpy, and there is no problem behind (checked).
Please help me. I have searched relentlessly how to find and replace a list of old words with a new list.

Thanks in advance

**Comment by MisterL2** [comment]
Hello and thanks for your comment!

You mention an **error** with filereplace() in the title; can you specify the error message?

I tried to reproduce the setup you describe, but it works as intended in my local experiment: 
(please ignore the setup :D )
![image](https://user-images.githubusercontent.com/46602881/117882837-04866380-b2ab-11eb-814d-33a6a6411fe5.png)
