### ISSUE TITLE
filereplace() specify path to save file as

### ISSUE THREAD

**Issue by mullimanko** [MisterL2/python-util#4]
Thank you for the handy function `filereplace()`. I would suggest to add an parameter to give the opportunity to save the edited file under a different name whereas the old file stays unedited. For example, `save_path` with the argument `None` (when the old file should be overwritten) or a specified path (when the file should be saved as).
Another nice thing would be that one could use a replacement dict as argument `rep={'zero':'0', 'temp':'bob', 'garbage':'nothing'}`.

**Comment by MisterL2** [comment]
Thanks for the suggestion, will work on it in when I have some time (hopefully in about a month's time)

**Comment by MisterL2** [comment]
I have implemented this feature now :)
There is a filereplace and a filereplace_multi, which accepts a dictionary. Outputfiles can also be specified.
filereplace_multi does not support regex though
