### ISSUE TITLE
filereplace( encoding= )

### ISSUE THREAD

**Issue by magsen** [MisterL2/python-util#5]
I encounter a problem using this package.
My file is encoding in "utf-8" but my environnement seems to be some ASCII extention.
By default the `open` method take automaticlly the env encoding (thus in many case it'll not break).

I resolve the problem by taking the code from the library and using `encoding="utf-8"` in the `open`.

The package methods may be modified by adding the encoding arg in all methods.
For exemple for filereplace:
```
def filereplace(filename, patternToReplace, replacementString, out=None, regex=False, encoding=None):
    with open(filename, 'r+', encoding=encoding) as f:
        file_content = f.read()
        if regex:
            from re import sub
            new_content = sub(patternToReplace,replacementString,file_content)
        else:
            new_content = file_content.replace(patternToReplace,replacementString)
        if out is None:
            f.seek(0)
            f.truncate(0)
            f.write(new_content)
        else:
            with open(out, 'w', encoding=encoding) as out_file:
                out_file.write(new_content) # Opening as 'w' means I overwrite all content in that file
```

**Comment by MisterL2** [comment]
Your system may be using [Windows-1252](https://stackoverflow.com/a/36316351/10802577) which is slightly different from utf-8. I added the proposal and committed it to the github, will take a little bit before I push it to PyPi tho
